services:
#  stats-server:
#    build: stats_svc
#    image: stats-server
#    container_name: stats-server
#    ports:
#      - "9090:9090"
#    depends_on:
#      - stats-db
#    entrypoint:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
#      - SPRING_DATASOURCE_USERNAME=stats
#      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:16.1
