DROP TABLE IF EXISTS endpoints_hit CASCADE;

CREATE TABLE IF NOT EXISTS endpoints_hit (
  id    BIGSERIAL    PRIMARY KEY,
  app  VARCHAR(120) NOT NULL,
  uri VARCHAR(512) NOT NULL,
  ip VARCHAR(50) NOT NULL,
  timestamp TIMESTAMP   WITHOUT TIME ZONE NOT NULL
);